### ISSUE TITLE
requirements on on-premises Exchange server

### ISSUE THREAD

**Issue by pokurt** [probits-as/MeetEasier#11]
hi i got myself a localhosted exchange server. do i really need to fill in oauth client id if i want to use exchange server locally?
its MS Exchange 2016

**Comment by fkmeland** [comment]
Sorry, didn't see this issue until now.

No, you only need set the following in your .env file:
EWS_USERNAME=
EWS_PASSWORD=
EWS_URI=
DOMAIN=example.com

SEARCH_USE_GRAPHAPI=false

Not sure if I have broken anything when we moved on to graph-api, you might be better off using the original project at: https://github.com/danxfisher/MeetEasier

Good luck :)
