### ISSUE TITLE
Only Loading

### ISSUE THREAD

**Issue by michaelortnersanube** [probits-as/MeetEasier#38]
Hello,

i have set up this application, but its loading and loading an no room comes to the list

![image](https://user-images.githubusercontent.com/96595501/225658700-b1aa3018-58e5-4655-b887-b82fc957906f.png)

We have a room named "Besprechungsraum" and is a ressource as a type of "room"

![image](https://user-images.githubusercontent.com/96595501/225658918-4343b382-78f3-49fb-be83-a7dbdabab899.png)

Where is the problem? Can someone help me?

**Comment by tomaskovacik** [comment]
It takes sometimes 48 hours for the room to be visible in graph API after creating it. So question is, when did you create the room?

**Comment by michaelortnersanube** [comment]
Hello Sir,

thanks for your really fast answer. I created the graph api for an hour, the room has been around for at least a year. What I have read that you have to add a room to a room list, is that also possible via the Office 365 portal, or does it have to be done via PowerShell?

**Comment by tomaskovacik** [comment]
well that would be probably the problem, I use PowerShell to do this, on Linux here is a how-to:

load powershell:
pwsh 

connect to exchange online:
PS>Connect-ExchangeOnline 

PS > Add-DistributionGroupMember -Identity Headquarters  -Member blablal@blall.com

how to create  distribution group as room list check this site:

https://learn.microsoft.com/en-us/outlook/troubleshoot/calendaring/configure-room-finder-rooms-workspaces

**Comment by michaelortnersanube** [comment]
Hello Sir,

I have now created a room list using Exchange Online.

For this I have used the following commands:

To create the room list:
New-DistributionGroup -Name "RoomList1" -RoomList

To get information about the room list:
Get-DistributionGroup-RoomList1|fl *Name*, *Recipe*.

And then add the room to the room list
Add-DistributionGroupMember -Identity roomlist1 -Member besprechungsraum@contoso.com

Then check if it is in the room list:
Get-DistributionGroupMember -Identity roomlist1

Unfortunately, it still loads permanently. Can it be that here also the changes can take a while? Or have I done something wrong and understood. Again for understanding, we have an existing meeting room with the name besprechungsraum@contoso.com.

Now I want to add this meeting room to a room list, I did that with above commands. I configured MeetEasier and made a new application in Azure, which also has all permissions. As described in the README.

![image](https://user-images.githubusercontent.com/96595501/225821943-00337adc-9f11-44fe-8f92-959ace69a236.png)

**Comment by michaelortnersanube** [comment]
And is this normal, that you can open the link for OAUT_AUTHORITY? 

![image](https://user-images.githubusercontent.com/96595501/225822415-315edd10-b93b-4f8f-a6cc-3771542cbbd3.png)

**Comment by tomaskovacik** [comment]
234234-234234-234234-234234 is not correct for sure :) there should be tenant ID

**Comment by michaelortnersanube** [comment]
Hello Sir,

yes i don't want to post the tenant id, so i have typed in some other things ;)

**Comment by michaelortnersanube** [comment]
So that there is no confusion in the configuration.

I have used the following for from the .env file:

OAUT_CLIENT_ID = Application (client) ID 
OAUTH_AUTHORITY = URL + Directory (tenant) ID
OAUTH_CLIENT_SECRET = Certificates & Secret -> VALUE

SEARCH_USE_GRAPHAPI=true
SEARCH_MAXROOMLISTS=10
SEARCH_MAXDAYS=10
SEARCH_MAXITEMS=6

PORT=8080

**Comment by michaelortnersanube** [comment]
Hello,

now its working. It has taked some time to apply all settings, thanks for the help!
